// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarterKit.Models;

#nullable disable

namespace StarterKit.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250113195253_CreateAdminsTable")]
    partial class CreateAdminsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("StarterKit.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("AdminId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            Email = "admin1@example.com",
                            Password = "$2a$11$cGkaBlMnjNaXYnd3JpDeTOZqDdDdh8eB1lpo9IbCctrbzqr1mLBzm",
                            UserName = "admin1"
                        },
                        new
                        {
                            AdminId = 2,
                            Email = "admin2@example.com",
                            Password = "$2a$11$NDMuJnu3IUu/I8dE2tRMaOtj9stQZWL6IDSwcVaU2gN6AIJ5mhwb.",
                            UserName = "admin2"
                        },
                        new
                        {
                            AdminId = 3,
                            Email = "admin3@example.com",
                            Password = "$2a$11$EaCSGGXJa5WK6Aknd5Fzg.86R0F2ZJbqzeLl7zJ0yFi1F1fmxbk7m",
                            UserName = "admin3"
                        },
                        new
                        {
                            AdminId = 4,
                            Email = "admin4@example.com",
                            Password = "$2a$11$zXwrdOLP/eda9MZaa4fhz.ztO7rxaR4.OW4WzB7B83qMJscASlota",
                            UserName = "admin4"
                        },
                        new
                        {
                            AdminId = 5,
                            Email = "admin5@example.com",
                            Password = "$2a$11$A6bW83oatCFcoNbt4pGrgOQd6k4IgOlaAq8I09KJWV2IFYq9ugh2G",
                            UserName = "admin5"
                        },
                        new
                        {
                            AdminId = 6,
                            Email = "admin6@example.com",
                            Password = "$2a$11$8h59.HYIuCkmlD4Ht2jgCOLIarsAtd8DPE5aPBKMlE7mCcp/QAal6",
                            UserName = "bisho"
                        },
                        new
                        {
                            AdminId = 7,
                            Email = "admin7@example.com",
                            Password = "$2a$11$1NaSczNvByy7izJ7xw/zWu.ajJIAmCW8Q.2ZpiRmatV0HeChqFrem",
                            UserName = "admin7"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
